### ISSUE TITLE
make docker fails for firecamp-cassandra-init

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#33]
[firecamp-cassandra-init.docker-build.log.gz](https://github.com/cloudstax/firecamp/files/1723647/firecamp-cassandra-init.docker-build.log.gz)

**Comment by JuniusLuo** [comment]
Fixed! To avoid this from happening again, will delete the original image and build from scratch next time.

**Comment by jazzl0ver** [comment]
Still having issues :(
[log.txt.gz](https://github.com/cloudstax/firecamp/files/1728302/log.txt.gz)

**Comment by JuniusLuo** [comment]
I tried it again. Works for me. Did you retry it? Could you please delete all local cassandra images and try it again?

**Comment by JuniusLuo** [comment]
Not sure why you still hit this issue. The cassandra dockerfile also includes the same build. After update the cassandra dockerfile to the latest, the init dockerfile could be built from cassandra dockerfile. The init task docker file could build from the cassandra dockerfile.

**Comment by JuniusLuo** [comment]
The patch was committed. Please let me know if you still have any issue to build the cassandra init docker image.

**Comment by jazzl0ver** [comment]
Your patch has solved the issue. Thank you!
